site_name: FlatImage Documentation
nav:
  - FlatImage: 
    - Getting Started: index.md
  - Examples:
    - Alpine:
      - Firefox: examples/alpine/firefox.md
    - Arch:
      - Firefox: examples/arch/firefox.md
      - Steam: examples/arch/steam.md
    - Blueprint:
      - Batocera: examples/blueprint/batocera.md
  - Commands:
    - fim-bind: cmd/bind.md
    - fim-boot: cmd/boot.md
    - fim-casefold: cmd/casefold.md
    - fim-desktop: cmd/desktop.md
    - fim-env: cmd/env.md
    - fim-exec: cmd/exec.md
    - fim-instance: cmd/instance.md
    - fim-layer: cmd/layer.md
    - fim-overlay: cmd/overlay.md
    - fim-notify: cmd/notify.md
    - fim-perms: cmd/perms.md
    - fim-recipe: cmd/recipe.md
    - fim-remote: cmd/remote.md
    - fim-root: cmd/root.md
    - fim-version: cmd/version.md
  - Portal:
    - Commands: portal/commands.md
  - Configuration:
    - User Identity: configuration/user-identity.md
    - Prompt: configuration/prompt.md
    - Compression: configuration/compression.md
    - Binding: configuration/binding.md
  - Architecture:
    - Environment: architecture/environment.md
    - Directories: architecture/directories.md
theme: readthedocs
