name: Release Linux (Gitea)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  #
  # Build
  #
  build:
    if: ${{ !contains(github.server_url, 'github.com') }}
    strategy:
      matrix:
        dist: [alpine,arch]
        arch: [x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build tools
        uses: ./.github/actions/install-build-tools

      - name: Build FlatImage
        uses: ./.github/actions/build-flatimage
        with:
          distribution: ${{ matrix.dist }}
          architecture: ${{ matrix.arch }}
          artifact-version: v3

  #
  # Test
  #
  test-doctest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run DocTest
        uses: ./.github/actions/test-doctest

  test-unittest:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        dist: [alpine,arch]
        arch: [x86_64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download built artifact
        uses: christopherhx/gitea-download-artifact@v4
        with:
          name: flatimage-${{ matrix.dist }}-${{ matrix.arch }}
          path: dist

      - name: Run UnitTest
        uses: ./.github/actions/test-unittest
        with:
          flatimage: dist/${{ matrix.dist }}_${{ matrix.arch }}.flatimage

  #
  # Release
  #
  release:
    runs-on: ubuntu-latest
    needs: [build, test-doctest, test-unittest]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: christopherhx/gitea-download-artifact@v4
        with:
          pattern: flatimage-*
          merge-multiple: true
          path: dist

      - name: Setup platform CLI
        uses: ./.github/actions/setup-platform-cli

      - name: Upload assets to Gitea Release
        run: |
          # Login
          tea login add \
            --name current \
            --url "${{ env.GITHUB_SERVER_URL }}" \
            --token "${{ secrets.GITHUB_TOKEN }}"
          # Upload
          tea release assets create \
            --login current \
            --repo ${{ github.repository }} \
            ${{ github.event.release.tag_name }} \
            dist/*