name: Release Linux (Gitea)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  #
  # Build
  #
  build:
    if: ${{ !contains(github.server_url, 'github.com') }}
    strategy:
      matrix:
        dist: [alpine]
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y tar xz-utils coreutils bc jo upx
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          mkdir -p dist
          sudo ./deploy/flatimage.sh ${{ matrix.dist }}
          cp ./build/dist/* ./dist
      - name: Upload flatimage
        uses: actions/upload-artifact@v3
        with:
          name: flatimage
          path: dist

  #
  # Release
  #
  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: flatimage
          path: dist

      - name: Install Gitea CLI (tea)
        run: |
          wget -O tea https://gitea.com/gitea/tea/releases/download/v0.11.1/tea-0.11.1-linux-amd64
          chmod +x tea
          sudo mv tea /usr/local/bin/

      - name: Upload assets to Gitea Release
        run: |
          # Login
          tea login add \
            --name current \
            --url "${{ env.GITHUB_SERVER_URL }}" \
            --token "${{ secrets.GITHUB_TOKEN }}"
          # Upload
          tea release assets create \
            --login current \
            --repo ${{ github.repository }} \
            ${{ github.event.release.tag_name }} \
            dist/*